In [8]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)
print(myvar[1], myvar['x'])

x    1
y    7
z    2
dtype: int64
7 1

In [12]:
df = pd.read_excel('../data/Forecast.xlsx')

df

,RID,Personnel Number,Resource Name,Project Role,2021-08-09 00:00:00,2021-08-16 00:00:00,2021-08-23 00:00:00,2021-08-30 00:00:00,2021-09-06 00:00:00,2021-09-13 00:00:00,...,2021-10-25 00:00:00,2021-11-01 00:00:00,2021-11-08 00:00:00,2021-11-15 00:00:00,2021-11-22 00:00:00,2021-11-29 00:00:00,2021-12-06 00:00:00,2021-12-13 00:00:00,2021-12-20 00:00:00,2021-12-27 00:00:00
0,1,50000289,Michael VanZuiden,Program/Project Manager,40.0,40.0,40.0,40.0,40.0,40.0,...,20.0,20.0,20.0,8.0,8.0,20.0,20.0,20.0,16.0,16.0
1,24,50000989,Jason Garcia,Project Manager,NaN,NaN,NaN,NaN,NaN,NaN,...,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0
2,26,50000533,Sabarinathan Lakshmanan,Offshore Mgr,NaN,NaN,NaN,NaN,5.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,50000415,Umashankar Poojar,PM offshore,NaN,NaN,NaN,NaN,NaN,NaN,...,36.0,9.0,36.0,45.0,45.0,45.0,45.0,45.0,45.0,45.0
4,3,50000171,Hector Koong,Architect,40.0,40.0,40.0,40.0,40.0,40.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,27,50002416_arch,Vipul Singh_arch,Architect,NaN,NaN,NaN,NaN,NaN,NaN,...,16.0,16.0,36.0,40.0,40.0,40.0,40.0,40.0,36.0,40.0
6,18,50002416,Vipul Singh,CRM Functional,40.0,40.0,40.0,40.0,40.0,40.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,6,50000229,Naga Sai Adithya Tadakamalla,SAP Functional Lead,NaN,NaN,NaN,NaN,NaN,NaN,...,40.0,40.0,40.0,40.0,24.0,40.0,40.0,40.0,32.0,32.0
8,4,50001202,Mansoob Khan,Functional - ISU Billing,40.0,40.0,40.0,40.0,40.0,40.0,...,40.0,40.0,40.0,40.0,0.0,24.0,40.0,40.0,0.0,0.0
9,5,50000045,Mallikarjuna Kanala,FICA Functional,40.0,40.0,40.0,40.0,40.0,40.0,...,40.0,40.0,40.0,40.0,40.0,40.0,40.0,0.0,0.0,40.0
10,7,50000636,Satya Reddy,Commerce Architect,40.0,40.0,40.0,40.0,24.0,24.0,...,24.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0
11,8,50000207,Jerry Hsu,Commerce Frontend,40.0,40.0,40.0,40.0,40.0,40.0,...,40.0,40.0,40.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0
12,9,50000551,Manjunatha Kashirudraiah,Commerce Frontend,NaN,NaN,NaN,NaN,45.0,45.0,...,45.0,36.0,27.0,45.0,45.0,27.0,45.0,45.0,45.0,45.0
13,10,50002452,Sandeep Deepak,Commerce Backend,NaN,NaN,NaN,NaN,45.0,45.0,...,45.0,27.0,45.0,45.0,45.0,45.0,45.0,45.0,45.0,27.0
14,11,50000377,Praveen Hamilpure,PWB,NaN,NaN,NaN,NaN,NaN,NaN,...,23.0,18.0,35.0,35.0,35.0,35.0,35.0,35.0,35.0,35.0
15,13,50000493,Ramesh Murthy,CPI Lead,NaN,NaN,NaN,NaN,40.0,40.0,...,20.0,5.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0
16,25,50002850,Maheen Latheef,CPI,NaN,NaN,NaN,NaN,NaN,NaN,...,45.0,18.0,45.0,45.0,45.0,45.0,45.0,45.0,36.0,36.0
17,15,50002879,Krishna Kanth,Developer - ISU,NaN,NaN,NaN,NaN,45.0,45.0,...,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,16,50002852,Silpa Yaragonda,Develolper - CRM,NaN,NaN,NaN,NaN,45.0,45.0,...,45.0,27.0,45.0,45.0,45.0,45.0,45.0,45.0,45.0,45.0
19,17,50003051,Mohammed Nabeel,Developer - ABAP,NaN,NaN,NaN,NaN,NaN,NaN,...,45.0,36.0,45.0,45.0,45.0,45.0,45.0,45.0,45.0,45.0
20,20,50000541,Athul Sukumar,Testing - Commerce/CRM,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,41.0,41.0,41.0,41.0,41.0,41.0,41.0,22.0
21,21,50001510,Vidhyasagar Ariharan,Testing - ISU Billing,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,20.0,20.0,20.0,20.0,40.0,35.0
22,22,50001512,Sreehari Nair,Testing - Bill Print,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,45.0,45.0,45.0,45.0,45.0,45.0
23,28,50000423,Ashwin Narayan,Developer - ISU,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,18.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,32,50003052,BIraja Samal,Developer - ABAP,NaN,NaN,NaN,NaN,NaN,NaN,...,36.0,36.0,45.0,45.0,45.0,45.0,45.0,45.0,45.0,45.0
25,31,50002606,Darshan Patil,Developer - ABAP,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,45.0,45.0,45.0,45.0,45.0,45.0
26,30,50002587,Shweta Sheelwant,Developer - ABAP,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,45.0,45.0,45.0,45.0,45.0,45.0
27,29,50000511,Nimal Nazaruddin,Developer - ISU,NaN,NaN,NaN,NaN,NaN,NaN,...,22.5,9.0,27.0,27.0,27.0,27.0,45.0,45.0,45.0,45.0
28,37,50001931,Subramanyam Borusu,Commerce Frontend,NaN,NaN,NaN,NaN,NaN,NaN,...,22.5,22.5,22.5,22.5,22.5,22.5,22.5,22.5,22.5,22.5
29,36,50000927,Kalpesh Jain,CRM Technico/Functional,NaN,NaN,NaN,NaN,NaN,NaN,...,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0
30,35,50000495,Vishall Pradeep,Developer - BW,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,22.5,22.5,22.5,22.5,22.5,22.5,22.5,22.5,18.0
31,34,50000389,Prashant Kalkar,Developer - BW,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,11.0,22.5,22.5,9.5,14.0,18.0,23.0,22.5,18.0
32,33,50000087,Paul Tseng,Developer - BW,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,20.0,40.0,0.0,0.0,32.0,40.0,20.0,0.0,0.0
33,38,50000073,Chuan Wang,BW/Reporting Architect,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.0,8.0,8.0,8.0,12.0,12.0,12.0,0.0
34,39,50000279,Ryan Esch,StreamServe/OT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,20.0,20.0,20.0,20.0,NaN,NaN,NaN
35,12,50000900,Srinivas Ellanki,StreamServe/OT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,10.0,20.0,20.0,40.0,40.0,40.0
36,40,50003053,Shadic Sherrif,PM offshore,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,35.0,35.0,35.0,35.0,35.0,35.0,35.0
37,41,50003101,Amardeep Kumar,CRM Developer,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df.columns

Index([              'RID',  'Personnel Number',     'Resource Name',
            'Project Role', 2021-08-09 00:00:00, 2021-08-16 00:00:00,
       2021-08-23 00:00:00, 2021-08-30 00:00:00, 2021-09-06 00:00:00,
       2021-09-13 00:00:00, 2021-09-20 00:00:00, 2021-09-27 00:00:00,
       2021-10-04 00:00:00, 2021-10-11 00:00:00, 2021-10-18 00:00:00,
       2021-10-25 00:00:00, 2021-11-01 00:00:00, 2021-11-08 00:00:00,
       2021-11-15 00:00:00, 2021-11-22 00:00:00, 2021-11-29 00:00:00,
       2021-12-06 00:00:00, 2021-12-13 00:00:00, 2021-12-20 00:00:00,
       2021-12-27 00:00:00],
      dtype='object')

In [17]:
df.iloc[0]

RID                                          1
Personnel Number                      50000289
Resource Name                Michael VanZuiden
Project Role           Program/Project Manager
2021-08-09 00:00:00                       40.0
2021-08-16 00:00:00                       40.0
2021-08-23 00:00:00                       40.0
2021-08-30 00:00:00                       40.0
2021-09-06 00:00:00                       40.0
2021-09-13 00:00:00                       40.0
2021-09-20 00:00:00                       20.0
2021-09-27 00:00:00                       20.0
2021-10-04 00:00:00                       20.0
2021-10-11 00:00:00                       20.0
2021-10-18 00:00:00                       20.0
2021-10-25 00:00:00                       20.0
2021-11-01 00:00:00                       20.0
2021-11-08 00:00:00                       20.0
2021-11-15 00:00:00                        8.0
2021-11-22 00:00:00                        8.0
2021-11-29 00:00:00                       20.0
2021-12-06 00:00:00                       20.0
2021-12-13 00:00:00                       20.0
2021-12-20 00:00:00                       16.0
2021-12-27 00:00:00                       16.0
Name: 0, dtype: object

In [18]:
df.iloc[0]['Resource Name']

'Michael VanZuiden'

In [19]:
# selecting multiple rows
df.iloc[[0, 1]]

,RID,Personnel Number,Resource Name,Project Role,2021-08-09 00:00:00,2021-08-16 00:00:00,2021-08-23 00:00:00,2021-08-30 00:00:00,2021-09-06 00:00:00,2021-09-13 00:00:00,...,2021-10-25 00:00:00,2021-11-01 00:00:00,2021-11-08 00:00:00,2021-11-15 00:00:00,2021-11-22 00:00:00,2021-11-29 00:00:00,2021-12-06 00:00:00,2021-12-13 00:00:00,2021-12-20 00:00:00,2021-12-27 00:00:00
0,1,50000289,Michael VanZuiden,Program/Project Manager,40.0,40.0,40.0,40.0,40.0,40.0,...,20.0,20.0,20.0,8.0,8.0,20.0,20.0,20.0,16.0,16.0
1,24,50000989,Jason Garcia,Project Manager,NaN,NaN,NaN,NaN,NaN,NaN,...,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0

In [20]:
df.iloc[[0, 1], 2]

0    Michael VanZuiden
1         Jason Garcia
Name: Resource Name, dtype: object

In [23]:
monthly_forecast_data = {
  'Personnel Number': ['50000289'],
  'Resource Name': ['Michael VanZuiden'],
  '1/2022': [189]
}

monthly_forecast_df = pd.DataFrame(monthly_forecast_data)

monthly_forecast_df

  Personnel Number      Resource Name       1/2022
0         50000289  Michael VanZuiden  [189, 1, 2]